/* Generated by Yosys 0.60 (git sha1 5bafeb77d, g++ 12.2.1 -fPIC -O3) */

module emulator_wrapper(clk_in, dut_hash_out, dut_out, dut_in, scan_out, scan_in, scan_enable_in);
  input [1:0] clk_in;
  wire [1:0] clk_in;
  output [63:0] dut_hash_out;
  wire [63:0] dut_hash_out;
  output [2:0] dut_out;
  wire [2:0] dut_out;
  input [2:0] dut_in;
  wire [2:0] dut_in;
  output [1:0] scan_out;
  wire [1:0] scan_out;
  input [1:0] scan_in;
  wire [1:0] scan_in;
  input scan_enable_in;
  wire scan_enable_in;
  sv_pipeline_2x2 dut (
    .\$scan_0_in (scan_in[0]),
    .\$scan_0_out (scan_out[0]),
    .\$scan_enable_in (scan_enable_in),
    .a_0_in(dut_in[0]),
    .a_1_in(dut_in[1]),
    .b_0_out(dut_out[0]),
    .b_1_out(dut_out[1]),
    .clk_in(clk_in[0])
  );
  assign dut_hash_out = 64'hffe3f722bffe252a;
endmodule

(* top =  1  *)
(* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:1.1-21.10" *)
module sv_pipeline_2x2(clk_in, a_0_in, a_1_in, b_0_out, b_1_out, \$scan_enable_in , \$scan_0_in , \$scan_0_out );
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:2.17-2.23" *)
  input clk_in;
  wire clk_in;
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:3.17-3.23" *)
  input a_0_in;
  wire a_0_in;
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:4.17-4.23" *)
  input a_1_in;
  wire a_1_in;
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:5.18-5.25" *)
  output b_0_out;
  reg b_0_out;
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:6.18-6.25" *)
  output b_1_out;
  reg b_1_out;
  input \$scan_enable_in ;
  wire \$scan_enable_in ;
  input \$scan_0_in ;
  wire \$scan_0_in ;
  output \$scan_0_out ;
  wire \$scan_0_out ;
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:13.5-20.8" *)
  wire \$0\a_1_stage2[0:0] ;
  wire \10 ;
  wire \12 ;
  wire \13 ;
  wire \15 ;
  wire \16 ;
  wire \18 ;
  wire \19 ;
  wire \21 ;
  wire \22 ;
  wire \24 ;
  wire \25 ;
  wire \9 ;
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:8.11-8.21" *)
  reg a_0_stage1;
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:10.11-10.21" *)
  reg a_0_stage2;
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:9.11-9.21" *)
  reg a_1_stage1;
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:11.11-11.21" *)
  reg a_1_stage2;
  assign \$0\a_1_stage2[0:0]  = ~ (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:17.23-17.34" *) a_1_stage1;
  (* \always_ff  = 32'd1 *)
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:13.5-20.8" *)
  always_ff @(posedge clk_in)
    b_0_out <= \10 ;
  (* \always_ff  = 32'd1 *)
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:13.5-20.8" *)
  always_ff @(posedge clk_in)
    b_1_out <= \16 ;
  (* \always_ff  = 32'd1 *)
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:13.5-20.8" *)
  always_ff @(posedge clk_in)
    a_0_stage1 <= \19 ;
  (* \always_ff  = 32'd1 *)
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:13.5-20.8" *)
  always_ff @(posedge clk_in)
    a_1_stage1 <= \13 ;
  (* \always_ff  = 32'd1 *)
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:13.5-20.8" *)
  always_ff @(posedge clk_in)
    a_0_stage2 <= \22 ;
  (* \always_ff  = 32'd1 *)
  (* src = "examples/sv/sv_pipeline_2x2/sv_pipeline_2x2.sv:13.5-20.8" *)
  always_ff @(posedge clk_in)
    a_1_stage2 <= \25 ;
  assign \10  = \$scan_enable_in  ? (* src = "scan chain data mux" *) \9  : a_0_stage2;
  assign \13  = \$scan_enable_in  ? (* src = "scan chain data mux" *) \12  : a_1_in;
  assign \16  = \$scan_enable_in  ? (* src = "scan chain data mux" *) \15  : a_1_stage2;
  assign \19  = \$scan_enable_in  ? (* src = "scan chain data mux" *) \18  : a_0_in;
  assign \22  = \$scan_enable_in  ? (* src = "scan chain data mux" *) \21  : a_0_stage1;
  assign \25  = \$scan_enable_in  ? (* src = "scan chain data mux" *) \24  : \$0\a_1_stage2[0:0] ;
  assign \18  = \$scan_0_in ;
  assign \15  = a_0_stage1;
  assign \9  = b_1_out;
  assign \21  = b_0_out;
  assign \24  = a_0_stage2;
  assign \12  = a_1_stage2;
  assign \$scan_0_out  = a_1_stage1;
endmodule
